### ISSUE TITLE
`atomist import github` fails

### ISSUE THREAD

**Issue by ludovicc** [atomist/sdm-local#185]
Hello,  I'm trying to run this command using Atomist 1.0.0-M3:

atomist import github hbpmedical

It does this:

```
Querying for repos at https://api.github.com/users/hbpmedical/repos?per_page=1000
Querying for repos at https://api.github.com/orgs/hbpmedical/repos?per_page=1000
✘ Error: Request failed with status code 401
    at createError (/home/ludo/opt/node-v8.9.4-linux-x64/lib/node_modules/@atomist/cli/node_modules/@atomist/sdm-local/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/ludo/opt/node-v8.9.4-linux-x64/lib/node_modules/@atomist/cli/node_modules/@atomist/sdm-local/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/ludo/opt/node-v8.9.4-linux-x64/lib/node_modules/@atomist/cli/node_modules/@atomist/sdm-local/node_modules/axios/lib/adapters/http.js:236:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at /home/ludo/opt/node-v8.9.4-linux-x64/lib/node_modules/@atomist/cli/node_modules/async-listener/glue.js:188:31
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

atomist clone command does not work either.

**Comment by cdupuis** [comment]
@ludovicc, Is that a private GitHub org? I guess we need to let you put in a token or alternatively use ssh for cloning.

**Comment by ludovicc** [comment]
No, the org is public and all repos in it are public. Many repos there are forks of other orgs.

**Comment by cdupuis** [comment]
@ludovicc do happen to have an `GITHUB_TOKEN` env var defined?

**Comment by ludovicc** [comment]
Yes indeed! I forgot about this env var, plus it's not for the organisation I was trying to checkout
