### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm-local#71]
build script should be
` ``
 "build": "npm-run-all compile test package:scripts",
```

Failure is:
```
> @atomist/sdm-local@0.1.3 test /Users/rodjohnson/sforzando-dev/idea-projects/slalom
> mocha --exit --require ts-node/register --require source-map-support/register "test/**/*.ts"

/Users/rodjohnson/sforzando-dev/idea-projects/slalom/node_modules/ts-node/src/index.ts:316
        throw new TypeError(
              ^
TypeError: Unable to require `.d.ts` file.
This is usually the result of a faulty configuration or import. Make sure there is a `.js`, `.json` or another executable extension and loader (attached before `ts-node`) available alongside `expandedTreeUtilsTest.d.ts`.
    at getOutput (/Users/rodjohnson/sforzando-dev/idea-projects/slalom/node_modules/ts-node/src/index.ts:316:15)
    at /Users/rodjohnson/sforzando-dev/idea-projects/slalom/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/Users/rodjohnson/sforzando-dev/idea-projects/slalom/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/Users/rodjohnson/sforzando-dev/idea-projects/slalom/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (module.js:660:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/rodjohnson/sforzando-dev/idea-projects/slalom/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at /Users/rodjohnson/sforzando-dev/idea-projects/slalom/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/rodjohnson/sforzando-dev/idea-projects/slalom/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/rodjohnson/sforzando-dev/idea-projects/slalom/node_modules/mocha/lib/mocha.js:536:10)
    at Object.<anonymous> (/Users/rodjohnson/sforzando-dev/idea-projects/slalom/node_modules/mocha/bin/_mocha:573:18)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3

```

**Comment by johnsonr** [comment]
Seems to be fixed
